// <auto-generated />
using System;
using AspNetCoreAPI.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreAPI.WebAPI.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20221030114614_SeedProductData")]
    partial class SeedProductData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreAPI.WebAPI.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 10, 25, 14, 46, 14, 503, DateTimeKind.Local).AddTicks(1330),
                            Name = "Computer",
                            Price = 15000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 10, 10, 14, 46, 14, 504, DateTimeKind.Local).AddTicks(360),
                            Name = "Phone",
                            Price = 10000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 9, 10, 14, 46, 14, 504, DateTimeKind.Local).AddTicks(378),
                            Name = "Keyboard",
                            Price = 1000m,
                            Stock = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
